### ISSUE TITLE
Promise  instead of callback

### ISSUE THREAD

**Issue by herberthenrique** [raulmangolin/mango-reactions#3]
Let's make work with `Promises` instead of `callback`?

**Comment by persocon** [comment]
why?

**Comment by herberthenrique** [comment]
http://callbackhell.com/
Kidding.

When someone is using mango-reactions he could have a better control of his application's flow.
better error handling, we could do something like:

``` javascript 
reactions()
  .then(doSomething)
  .then(doOtherStuff)
  .catch(errorHandling)
```

And if you're using ES7, `async/await` will work properly with promises :)

**Comment by raulmangolin** [comment]
I don't see any use for this package instead a Live Streaming Poll so I don't think it's strictly necessary, but I don't see any problem to use promises. 

Feel free to send a pull request and help us

**Comment by herberthenrique** [comment]
You're right, if this callback function it's gonna be called `n` times
