### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by herberthenrique** [raulmangolin/mango-reactions#5]
Proper error handling.
`throw new Error(message)`

**Comment by persocon** [comment]
this still has to be done ?

**Comment by herberthenrique** [comment]
Nop, 
just waiting @raulmangolin approve #9

**Comment by herberthenrique** [comment]
btw, i was reading this issue and @raulmangolin was right... i was drunk while writing this thing

**Comment by persocon** [comment]
@herberthenrique Raul's disseminating his alcoholic behavior around HAHAHA

**Comment by herberthenrique** [comment]
@persocon in portuguese, we have the word `mangolizar`.
The translation to english is something like "GET DRUNK LIKE A RETARD"

**Comment by raulmangolin** [comment]
The right verb is [mangolinizar](http://www.dicionarioinformal.com.br/mangolinizar/)

**Comment by raulmangolin** [comment]
Done and merged with Patch 2 #9
